name: py38
channels:
  - pytorch
  - conda-forge
  - fastai
  - defaults
dependencies:
  - _pytorch_select=0.1
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bleach=3.1.5
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2020.6.24
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fastai=1.0.61
  - fastprogress=0.2.4
  - freetype=2.10.2
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.0.2
  - jupyter_client=6.1.6
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=2.1.5
  - jupyterlab_server=1.2.0
  - kiwisolver=1.2.0
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.5.2
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - murmurhash=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - ninja=1.10.0
  - notebook=6.0.3
  - numexpr=2.7.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - nvidia-ml-py3=7.352.0
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - plac=0.9.6
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.4.0
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - readline=8.0
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.2.0
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.32.3
  - srsly=1.0.2
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.4.1
  - tk=8.6.10
  - torchvision=0.5.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.9.0
    - aiodns==2.0.0
    - aiohttp==3.6.2
    - altair==4.1.0
    - arviz==0.9.0
    - astor==0.8.1
    - async-timeout==3.0.1
    - autograd==1.3
    - autograd-gamma==0.4.2
    - autopep8==1.5.3
    - base58==2.0.1
    - blinker==1.4
    - boto3==1.14.33
    - botocore==1.17.33
    - bs4==0.0.1
    - cachetools==4.1.1
    - cchardet==2.1.6
    - cftime==1.2.1
    - click==7.1.2
    - cmdstanpy==0.9.5
    - cytoolz==0.10.1
    - descartes==1.1.0
    - dill==0.3.2
    - docutils==0.15.2
    - enum-compat==0.0.3
    - fastapi==0.60.1
    - fastscript==0.1.5
    - finetune==0.8.6
    - fire==0.3.1
    - flake8==3.8.3
    - ftfy==5.8
    - future==0.18.2
    - google-api-core==1.22.0
    - google-auth==1.20.0
    - google-auth-oauthlib==0.4.1
    - google-cloud-bigquery==1.26.1
    - google-cloud-core==1.3.0
    - google-crc32c==0.1.0
    - google-resumable-media==0.7.0
    - googleapis-common-protos==1.52.0
    - grpcio==1.30.0
    - h11==0.9.0
    - h5py==2.10.0
    - httptools==0.1.1
    - hypothesis==5.23.8
    - imbalanced-learn==0.6.2
    - iniconfig==1.0.1
    - ipywidgets==7.5.1
    - jax==0.1.75
    - jaxlib==0.1.52
    - jellyfish==0.8.2
    - jmespath==0.10.0
    - joblib==0.16.0
    - jupyter==1.0.0
    - jupyter-console==6.1.0
    - lifelines==0.25.0
    - lifetimes==0.11.3
    - markdown==3.2.2
    - mccabe==0.6.1
    - mizani==0.7.1
    - more-itertools==8.4.0
    - multidict==4.7.6
    - mypy==0.782
    - mypy-extensions==0.4.3
    - nbdev==0.2.20
    - netcdf4==1.5.4
    - networkx==2.4
    - nltk==3.5
    - nmslib==2.0.6
    - numpyro==0.3.0
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - palettable==3.3.0
    - pandas==1.1.0
    - pandas-gbq==0.13.2
    - pathtools==0.1.2
    - patsy==0.5.1
    - plotnine==0.7.0
    - pluggy==0.13.1
    - protobuf==3.12.4
    - psutil==5.7.2
    - py==1.9.0
    - pyaml==20.4.0
    - pyarrow==1.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.5.0
    - pycares==3.1.1
    - pycodestyle==2.6.0
    - pydantic==1.6.1
    - pydata-google-auth==1.1.0
    - pydeck==0.4.0
    - pyemd==0.5.1
    - pyflakes==2.2.0
    - pymc3==3.9.2
    - pyphen==0.9.5
    - pysbd==0.2.3
    - pytest==6.0.1
    - pytorch-lightning==0.8.5
    - qtconsole==4.7.5
    - qtpy==1.9.0
    - regex==2020.7.14
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s3transfer==0.3.3
    - scikit-learn==0.23.1
    - scikit-misc==0.1.3
    - scikit-optimize==0.7.4
    - scipy==1.5.2
    - scispacy==0.2.5
    - skorch==0.8.0
    - sortedcontainers==2.2.2
    - spacy==2.3.2
    - spacy-lookups-data==0.3.2
    - starlette==0.13.6
    - statsmodels==0.11.1
    - streamlit==0.64.0
    - tabulate==0.8.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - textacy==0.10.0
    - theano==1.0.5
    - threadpoolctl==2.1.0
    - toml==0.10.1
    - toolz==0.10.0
    - tqdm==4.48.0
    - typed-ast==1.4.1
    - typer==0.3.1
    - typing-extensions==3.7.4.2
    - tzlocal==2.1
    - ujson==3.0.0
    - uvicorn==0.11.8
    - uvloop==0.14.0
    - validators==0.16.0
    - vega==3.4.0
    - watchdog==0.10.3
    - websockets==8.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - xarray==0.16.0
    - xgboost==1.1.1
    - yarl==1.5.1
