name: py38
channels:
  - defaults
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.8 # python version
  - pip
  - notebook
  - jupyterlab
  - nb_conda
  - jupyter_contrib_nbextensions
  - fastai
  - pytorch
  - torchvision
  - pip:
    - aiohttp[speedups]
    - autopep8
    - altair
    - cmdstanpy[all]
    - fastapi
    - finetune
    - fire
    - flake8
    - hypothesis
    - jax
    - jaxlib
    - lifelines
    - lifetimes
    - mypy
    - networkx
    - nbdev
    - numpy
    - numpyro
    - pandas
    - pandas-gbq
    - plotnine[all]
    - pydata-google-auth
    - pymc3
    - pytest
    - pytorch-lightning
    - scikit-learn
    - scikit-optimize
    - scipy
    - scispacy
    - skorch
    - spacy
    - spacy-lookups-data
    - statsmodels
    - streamlit
    - textacy
    - tqdm
    - typer
    - uvicorn
    - vega
    - xgboost
