name: py38
channels:
  - pytorch
  - conda-forge
  - fastai
  - defaults
dependencies:
  - _pytorch_select=0.1
  - absl-py=0.9.0
  - aiohttp=3.6.2
  - appnope=0.1.0
  - arviz=0.6.1
  - async-timeout=3.0.1
  - attrs=19.3.0
  - autopep8=1.5.3
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bleach=3.1.5
  - blinker=1.4
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.6.24
  - cachetools=4.1.0
  - catalogue=1.0.0
  - cctools=927.0.2
  - certifi=2020.6.20
  - cffi=1.14.0
  - cftime=1.1.2
  - chardet=3.0.4
  - clang=10.0.0
  - clang_osx-64=10.0.0
  - clangxx=10.0.0
  - clangxx_osx-64=10.0.0
  - click=7.1.2
  - compiler-rt=10.0.0
  - compiler-rt_osx-64=10.0.0
  - cryptography=2.9.2
  - curl=7.71.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - fastai=1.0.61
  - fastprogress=0.2.3
  - fire=0.3.1
  - flake8=3.8.3
  - freetype=2.10.2
  - future=0.18.2
  - google-api-core=1.17.0
  - google-auth=1.17.2
  - google-auth-oauthlib=0.4.1
  - google-cloud-bigquery=1.22.0
  - google-cloud-core=1.3.0
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - grpcio=1.16.1
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2019.4
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter_client=6.1.6
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - kiwisolver=1.2.0
  - krb5=1.18.2
  - lcms2=2.11
  - ld64=450.3
  - libcurl=7.71.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libllvm10=10.0.0
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvm-openmp=10.0.0
  - llvm-tools=10.0.0
  - lxml=4.5.2
  - lz4-c=1.9.2
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mizani=0.7.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - more-itertools=8.4.0
  - multidict=4.7.3
  - murmurhash=1.0.2
  - mypy=0.782
  - mypy_extensions=0.4.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - netcdf4=1.5.3
  - networkx=2.4
  - ninja=1.9.0
  - notebook=6.0.3
  - numexpr=2.7.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - nvidia-ml-py3=7.352.0
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - palettable=3.3.0
  - pandas=1.0.5
  - pandas-gbq=0.13.2
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - plac=0.9.6
  - plotnine=0.7.0
  - pluggy=0.13.1
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - protobuf=3.12.3
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyaml=19.4.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydata-google-auth=1.1.0
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pymc3=3.8
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.3
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.4.0
  - pytorch-lightning=0.8.5
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scikit-optimize=0.7.4
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.2.0
  - six=1.15.0
  - skorch=0.8.0
  - soupsieve=2.0.1
  - spacy=2.3.1
  - spacy-lookups-data=0.3.0
  - sqlite=3.32.3
  - srsly=1.0.2
  - statsmodels=0.11.1
  - tabulate=0.8.3
  - tapi=1000.10.8
  - tensorboard=2.0.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - theano=1.0.4
  - thinc=7.4.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.5.0
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xarray=0.15.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.0.1
    - boto3==1.14.22
    - botocore==1.17.22
    - bs4==0.0.1
    - cmdstanpy==0.9.5
    - cytoolz==0.10.1
    - docutils==0.15.2
    - enum-compat==0.0.3
    - fastapi==0.59.0
    - fastcache==1.1.0
    - fastscript==0.1.4
    - finetune==0.8.6
    - ftfy==5.7
    - h11==0.9.0
    - httptools==0.1.1
    - hypothesis==5.19.3
    - imbalanced-learn==0.6.2
    - ipywidgets==7.5.1
    - jax==0.1.57
    - jaxlib==0.1.37
    - jellyfish==0.8.2
    - jmespath==0.10.0
    - jupyter==1.0.0
    - jupyter-console==6.1.0
    - nbdev==0.2.18
    - nltk==3.5
    - nmslib==2.0.6
    - numpyro==0.2.4
    - opt-einsum==3.2.1
    - pathtools==0.1.2
    - pyarrow==0.17.1
    - pybind11==2.5.0
    - pydantic==1.6.1
    - pydeck==0.4.0b2
    - pyemd==0.5.1
    - pyphen==0.9.5
    - pysbd==0.2.3
    - qtconsole==4.7.5
    - qtpy==1.9.0
    - regex==2020.7.14
    - s3transfer==0.3.3
    - scikit-learn==0.22
    - scispacy==0.2.5
    - sortedcontainers==2.2.2
    - starlette==0.13.4
    - streamlit==0.63.0
    - textacy==0.10.0
    - toolz==0.10.0
    - typer==0.3.0
    - tzlocal==2.1
    - ujson==3.0.0
    - uvicorn==0.11.5
    - uvloop==0.14.0
    - validators==0.16.0
    - vega==3.4.0
    - watchdog==0.10.3
    - websockets==8.1
    - widgetsnbextension==3.5.1
    - xgboost==1.1.1

